### ISSUE TITLE
Do fizzbuzz with if, for statements

### ISSUE THREAD

**Issue by Jayone12** [Jayone12/team-fizzbuzz#1]
## Tasks
- [x] Print 'fizz' if i is times of 3
- [x] Print 'buzz' if i is times of 5
- [x] Print 'fizzbuzz' if i is times of 15
- [x] else, print i itself.
